//! `jm new <recipe>` の end-to-end。MockExecutor 不要(render まで)。
//! live SLURM 不要。

use assert_cmd::Command;
use std::fs;
use std::path::{Path, PathBuf};

fn jm() -> Command {
    let mut c = Command::cargo_bin("jm").unwrap();
    c.arg("--root");
    c
}

fn walk(root: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(rd) = fs::read_dir(root) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() {
                walk(&p, out);
            } else {
                out.push(p);
            }
        }
    }
}

fn scaffold_print_path(root: &tempfile::TempDir, extra: &[&str]) -> PathBuf {
    let mut c = jm();
    c.arg(root.path())
        .arg("new")
        .args(extra)
        .arg("--print-path");
    let out = c.assert().success();
    let p = String::from_utf8(out.get_output().stdout.clone()).unwrap();
    PathBuf::from(p.trim().to_string())
}

fn normalize(s: &str) -> String {
    s.lines()
        .filter(|l| {
            !l.starts_with("uuid")
                && !l.starts_with("created_at")
                && !l.starts_with("# Generated by")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn list_and_describe_do_not_scaffold() {
    let root = tempfile::tempdir().unwrap();
    jm().arg(root.path())
        .args(["new", "--list"])
        .assert()
        .success()
        .stdout(predicates::str::contains("g16-opt-parse"))
        .stdout(predicates::str::contains("blank"));
    jm().arg(root.path())
        .args(["new", "g16-opt-parse", "--describe"])
        .assert()
        .success()
        .stdout(predicates::str::contains("opt -> parse [afterok]"));
    assert_eq!(fs::read_dir(root.path()).unwrap().count(), 0);
}

#[test]
fn scaffold_g16_opt_parse_writes_all_files() {
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["g16-opt-parse", "--param", "opt.charge=1"]);

    let flow = fs::read_to_string(dir.join("flow.toml")).unwrap();
    assert!(flow.contains("[jobs.opt]") && flow.contains("[jobs.parse]"));
    // R4: flow.toml body has NO cd; launches via the $JM_JOB_DIR env var.
    assert!(
        !flow.contains("cd "),
        "R4: flow.toml must not cd; got:\n{flow}"
    );
    // R4: env-var launcher, no absolute flow_dir path baked.
    assert!(
        flow.contains("bash \"$JM_JOB_DIR/scripts/opt.bash\""),
        "flow.toml body must use the $JM_JOB_DIR launcher; got:\n{flow}"
    );
    assert!(
        !flow.contains(&dir.display().to_string()),
        "R4: flow.toml must not bake the absolute flow_dir path; got:\n{flow}"
    );

    let gjf = fs::read_to_string(dir.join("opt/input/main.gjf")).unwrap();
    assert!(gjf.contains("1 1"));
    assert!(!gjf.contains("%rwf"));

    let optbash = fs::read_to_string(dir.join("opt/scripts/opt.bash")).unwrap();
    assert!(optbash.contains("unset -f conda"));
    assert!(optbash.contains("module restore gaussian_A -f"));
    assert!(optbash.contains("python \"$JM_JOB_DIR/scripts/run.py\""));
    assert!(
        !optbash.contains(&dir.display().to_string()),
        "R4: opt.bash must not bake an absolute path"
    );
    assert!(!optbash.contains("srun"));

    assert!(dir.join("opt/scripts/run.py").exists());
    assert!(dir.join("parse/scripts/parse.py").exists());

    // R4: JOB_DIR read from env, no {{JOB_DIR}} sentinel, no absolute path
    // baked, os.getcwd() never used (cwd-independent like run-g16).
    let runpy = fs::read_to_string(dir.join("opt/scripts/run.py")).unwrap();
    assert!(runpy.contains("JOB_DIR = os.environ[\"JM_JOB_DIR\"]"));
    assert!(!runpy.contains("{{JOB_DIR}}"));
    assert!(!runpy.contains("os.getcwd()"));
    assert!(
        !runpy.contains(&dir.display().to_string()),
        "R4: run.py must not bake the absolute flow_dir path"
    );
    let parsepy = fs::read_to_string(dir.join("parse/scripts/parse.py")).unwrap();
    assert!(parsepy.contains("JOB_DIR = os.environ[\"JM_JOB_DIR\"]"));
    assert!(!parsepy.contains("{{JOB_DIR}}"));

    // stage 2b: per-task common.toml carries the site config (read by run.py).
    let optcommon = fs::read_to_string(dir.join("opt/common.toml")).unwrap();
    assert!(optcommon.contains("launcher       = \"srun\""));
    assert!(optcommon.contains("g16_cmd        = \"g16\""));
    assert!(optcommon.contains("module_profile = \"gaussian_A\""));
    assert!(
        !optcommon.contains(&dir.display().to_string()),
        "R4: common.toml must not bake an absolute flow_dir path"
    );
    let parsecommon = fs::read_to_string(dir.join("parse/common.toml")).unwrap();
    assert!(parsecommon.contains("module_profile = \"default\""));
    // stage 2b: site config left plan.toml.
    let plan = fs::read_to_string(dir.join("plan.toml")).unwrap();
    assert!(
        !plan.contains("launcher"),
        "plan.toml must not carry launcher"
    );
    assert!(plan.contains("route"), "plan.toml keeps experiment params");

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let m = fs::metadata(dir.join("opt/scripts/run.py")).unwrap();
        assert_eq!(m.permissions().mode() & 0o777, 0o755);
    }
}

#[test]
fn r4_scaffold_bakes_no_absolute_flow_dir_path() {
    // R4 invariant (spec §9): regardless of whether `--root` is relative or
    // absolute, the scaffold output must contain NO absolute flow_dir path —
    // paths resolve from $JM_JOB_DIR (exported by batch.bash) at job runtime.
    let root = tempfile::tempdir().unwrap();
    let mut c = jm();
    c.current_dir(root.path()) // cwd = tempdir; pass `--root .` (relative)
        .arg(".")
        .arg("new")
        .arg("g16-opt-parse")
        .arg("--print-path");
    let out = c.assert().success();
    let printed = String::from_utf8(out.get_output().stdout.clone()).unwrap();
    let dir = PathBuf::from(printed.trim());

    let abs_dir = if dir.is_absolute() {
        dir.clone()
    } else {
        root.path().join(&dir)
    };
    let abs_prefix = root.path().display().to_string();

    // run.py / parse.py read JOB_DIR from the environment, never bake an abs path.
    let runpy = fs::read_to_string(abs_dir.join("opt/scripts/run.py")).unwrap();
    assert!(runpy.contains("JOB_DIR = os.environ[\"JM_JOB_DIR\"]"));
    let parsepy = fs::read_to_string(abs_dir.join("parse/scripts/parse.py")).unwrap();
    assert!(parsepy.contains("JOB_DIR = os.environ[\"JM_JOB_DIR\"]"));

    // No scaffold-authored file (flow.toml / plan.toml / scripts) may contain
    // the absolute tempdir prefix.
    for rel in [
        "flow.toml",
        "plan.toml",
        "opt/scripts/opt.bash",
        "opt/scripts/run.py",
        "opt/common.toml",
        "parse/scripts/parse.bash",
        "parse/scripts/parse.py",
        "parse/common.toml",
    ] {
        let body = fs::read_to_string(abs_dir.join(rel)).unwrap();
        assert!(
            !body.contains(&abs_prefix),
            "R4 invariant: {rel} leaked the absolute flow_dir prefix {abs_prefix:?}"
        );
    }
}

#[test]
fn input_coordinate_xyz_is_copied_and_injected() {
    let root = tempfile::tempdir().unwrap();
    let xyz = root.path().join("mol.xyz");
    fs::write(&xyz, "1\nc\nO 0.0 0.0 0.0\n").unwrap();
    let dir = scaffold_print_path(
        &root,
        &[
            "g16-opt-parse",
            "--param",
            &format!("opt.input_coordinate={}", xyz.display()),
        ],
    );
    assert!(dir.join("opt/input/mol.xyz").exists());
    let gjf = fs::read_to_string(dir.join("opt/input/main.gjf")).unwrap();
    assert!(gjf.contains("O 0.000000 0.000000 0.000000"));
}

#[test]
fn missing_input_coordinate_fails_and_rolls_back() {
    let root = tempfile::tempdir().unwrap();
    jm().arg(root.path())
        .args([
            "new",
            "g16-opt-parse",
            "--param",
            "opt.input_coordinate=/no/such/file.xyz",
        ])
        .assert()
        .failure();
    assert_eq!(fs::read_dir(root.path()).unwrap().count(), 0);
}

#[test]
fn scaffold_then_render_succeeds_and_injects_jm_job_dir() {
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["g16-opt-parse"]);
    let uuid = dir.file_name().unwrap().to_string_lossy().into_owned();

    jm().arg(root.path())
        .args(["doctor", &uuid])
        .assert()
        .success();
    jm().arg(root.path())
        .args(["render", &uuid])
        .assert()
        .success();

    // stage 2b: launcher/g16_cmd left plan.toml for common.toml, so render no
    // longer bakes JM_PARAM_LAUNCHER. Instead it injects the R4 path env.
    let mut files = Vec::new();
    walk(&dir, &mut files);
    let batches: Vec<String> = files
        .iter()
        .filter(|p| p.ends_with("batch.bash"))
        .filter_map(|p| fs::read_to_string(p).ok())
        .collect();
    assert!(!batches.is_empty(), "render must produce batch.bash files");
    assert!(
        batches.iter().any(|s| s.contains("export JM_JOB_DIR=")),
        "render must inject export JM_JOB_DIR (R4)"
    );
    assert!(
        batches.iter().all(|s| !s.contains("JM_PARAM_LAUNCHER")),
        "stage 2b: launcher moved to common.toml; must not bake JM_PARAM_LAUNCHER"
    );
}

#[test]
fn bare_jm_new_is_byte_identical_to_blank() {
    let ra = tempfile::tempdir().unwrap();
    let rb = tempfile::tempdir().unwrap();
    let pa = scaffold_print_path(&ra, &[]);
    let pb = scaffold_print_path(&rb, &["blank"]);
    let fa = normalize(&fs::read_to_string(pa.join("flow.toml")).unwrap());
    let fb = normalize(&fs::read_to_string(pb.join("flow.toml")).unwrap());
    assert_eq!(fa, fb);
}

#[test]
fn blank_plan_toml_parses_as_experiment_plan() {
    // Restores coverage of the deleted jm.rs `plan_template_parses_as_experiment_plan`.
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["blank"]);
    let plan_str = fs::read_to_string(dir.join("plan.toml")).unwrap();
    let _: job_manager::plan::ExperimentPlan =
        toml::from_str(&plan_str).expect("blank plan.toml must parse as ExperimentPlan");
}

#[test]
fn blank_tag_is_rendered_and_flow_still_parses_as_jobflow() {
    // Restores coverage of the deleted jm.rs `flow_template_renders_tags_section`.
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["blank", "--tag", "owner=alice"]);
    let flow_str = fs::read_to_string(dir.join("flow.toml")).unwrap();
    assert!(
        flow_str.contains("owner = \"alice\""),
        "non-empty [tags] section must render the tag; got:\n{flow_str}"
    );
    // Still a valid JobFlow with the tag present.
    let _: gaussian_job_shared::entities::workflow::JobFlow =
        toml::from_str(&flow_str).expect("blank flow.toml with a tag must parse as JobFlow");
}
