//! `jm new <recipe>` の end-to-end。MockExecutor 不要(render まで)。
//! live SLURM 不要。

use assert_cmd::Command;
use std::fs;
use std::path::{Path, PathBuf};

fn jm() -> Command {
    let mut c = Command::cargo_bin("jm").unwrap();
    c.arg("--root");
    c
}

fn walk(root: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(rd) = fs::read_dir(root) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() {
                walk(&p, out);
            } else {
                out.push(p);
            }
        }
    }
}

fn scaffold_print_path(root: &tempfile::TempDir, extra: &[&str]) -> PathBuf {
    let mut c = jm();
    c.arg(root.path())
        .arg("new")
        .args(extra)
        .arg("--print-path");
    let out = c.assert().success();
    let p = String::from_utf8(out.get_output().stdout.clone()).unwrap();
    PathBuf::from(p.trim().to_string())
}

fn normalize(s: &str) -> String {
    s.lines()
        .filter(|l| {
            !l.starts_with("uuid")
                && !l.starts_with("created_at")
                && !l.starts_with("# Generated by")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn list_and_describe_do_not_scaffold() {
    let root = tempfile::tempdir().unwrap();
    jm().arg(root.path())
        .args(["new", "--list"])
        .assert()
        .success()
        .stdout(predicates::str::contains("g16-opt-parse"))
        .stdout(predicates::str::contains("blank"));
    jm().arg(root.path())
        .args(["new", "g16-opt-parse", "--describe"])
        .assert()
        .success()
        .stdout(predicates::str::contains("opt -> parse [afterok]"));
    assert_eq!(fs::read_dir(root.path()).unwrap().count(), 0);
}

#[test]
fn scaffold_g16_opt_parse_writes_all_files() {
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["g16-opt-parse", "--param", "opt.charge=1"]);

    let flow = fs::read_to_string(dir.join("flow.toml")).unwrap();
    assert!(flow.contains("[jobs.opt]") && flow.contains("[jobs.parse]"));
    // R3': flow.toml body has NO cd; absolute job dir is baked into run.py.
    assert!(
        !flow.contains("cd "),
        "R3': flow.toml must not cd; got:\n{flow}"
    );
    // R3' (a): absolute launcher path, never the relative form (H1 fix).
    assert!(
        flow.contains(&format!("bash \"{}/opt/scripts/opt.bash\"", dir.display())),
        "flow.toml body must use absolute launcher; got:\n{flow}"
    );
    assert!(
        !flow.contains("bash scripts/opt.bash"),
        "H1 regression: flow.toml must not use a relative launcher; got:\n{flow}"
    );

    let gjf = fs::read_to_string(dir.join("opt/input/main.gjf")).unwrap();
    assert!(gjf.contains("1 1"));
    assert!(!gjf.contains("%rwf"));

    let optbash = fs::read_to_string(dir.join("opt/scripts/opt.bash")).unwrap();
    assert!(optbash.contains("unset -f conda"));
    assert!(optbash.contains("module restore gaussian_A -f"));
    assert!(optbash.contains(&format!("python \"{}/opt/scripts/run.py\"", dir.display())));
    assert!(
        !optbash.contains("python scripts/run.py"),
        "H1 regression: opt.bash must launch run.py by absolute path"
    );
    assert!(!optbash.contains("srun"));

    assert!(dir.join("opt/scripts/run.py").exists());
    assert!(dir.join("parse/scripts/parse.py").exists());

    // R3': the absolute job dir is baked into run.py/parse.py, sentinel
    // swapped, and os.getcwd() never used (cwd-independent like run-g16).
    let runpy = fs::read_to_string(dir.join("opt/scripts/run.py")).unwrap();
    assert!(runpy.contains(&format!("JOB_DIR = \"{}/opt\"", dir.display())));
    assert!(!runpy.contains("{{JOB_DIR}}"));
    assert!(!runpy.contains("os.getcwd()"));
    let parsepy = fs::read_to_string(dir.join("parse/scripts/parse.py")).unwrap();
    assert!(parsepy.contains(&format!("JOB_DIR = \"{}/parse\"", dir.display())));
    assert!(!parsepy.contains("{{JOB_DIR}}"));

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let m = fs::metadata(dir.join("opt/scripts/run.py")).unwrap();
        assert_eq!(m.permissions().mode() & 0o777, 0o755);
    }
}

#[test]
fn r3prime_job_dir_is_absolute_even_with_relative_root() {
    // R3' invariant regression: a relative `--root` must still bake an
    // ABSOLUTE JOB_DIR (otherwise it re-resolves against SLURM's cwd).
    let root = tempfile::tempdir().unwrap();
    let mut c = jm();
    c.current_dir(root.path()) // cwd = tempdir; pass `--root .` (relative)
        .arg(".")
        .arg("new")
        .arg("g16-opt-parse")
        .arg("--print-path");
    let out = c.assert().success();
    let printed = String::from_utf8(out.get_output().stdout.clone()).unwrap();
    let dir = PathBuf::from(printed.trim());

    let runpy_path = if dir.is_absolute() {
        dir.join("opt/scripts/run.py")
    } else {
        root.path().join(&dir).join("opt/scripts/run.py")
    };
    let runpy = fs::read_to_string(&runpy_path).unwrap();
    // The JOB_DIR literal must start with the absolute tempdir prefix and
    // must not be the relative "./..." form.
    let job_dir_line = runpy
        .lines()
        .find(|l| l.starts_with("JOB_DIR = "))
        .expect("run.py must define JOB_DIR");
    let baked = job_dir_line
        .trim_start_matches("JOB_DIR = \"")
        .trim_end_matches('"');
    assert!(
        Path::new(baked).is_absolute(),
        "R3': baked JOB_DIR must be absolute, got {baked:?}"
    );
    assert!(baked.ends_with("/opt"), "got {baked:?}");
    assert!(
        !baked.starts_with("./") && !baked.starts_with("."),
        "got {baked:?}"
    );
}

#[test]
fn input_coordinate_xyz_is_copied_and_injected() {
    let root = tempfile::tempdir().unwrap();
    let xyz = root.path().join("mol.xyz");
    fs::write(&xyz, "1\nc\nO 0.0 0.0 0.0\n").unwrap();
    let dir = scaffold_print_path(
        &root,
        &[
            "g16-opt-parse",
            "--param",
            &format!("opt.input_coordinate={}", xyz.display()),
        ],
    );
    assert!(dir.join("opt/input/mol.xyz").exists());
    let gjf = fs::read_to_string(dir.join("opt/input/main.gjf")).unwrap();
    assert!(gjf.contains("O 0.000000 0.000000 0.000000"));
}

#[test]
fn missing_input_coordinate_fails_and_rolls_back() {
    let root = tempfile::tempdir().unwrap();
    jm().arg(root.path())
        .args([
            "new",
            "g16-opt-parse",
            "--param",
            "opt.input_coordinate=/no/such/file.xyz",
        ])
        .assert()
        .failure();
    assert_eq!(fs::read_dir(root.path()).unwrap().count(), 0);
}

#[test]
fn scaffold_then_render_succeeds_and_bakes_jm_params() {
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["g16-opt-parse"]);
    let uuid = dir.file_name().unwrap().to_string_lossy().into_owned();

    jm().arg(root.path())
        .args(["doctor", &uuid])
        .assert()
        .success();
    jm().arg(root.path())
        .args(["render", &uuid])
        .assert()
        .success();

    let mut files = Vec::new();
    walk(&dir, &mut files);
    let baked = files.iter().any(|p| {
        p.ends_with("batch.bash")
            && fs::read_to_string(p)
                .map(|s| s.contains("export JM_PARAM_LAUNCHER='srun'"))
                .unwrap_or(false)
    });
    assert!(baked, "render must bake export JM_PARAM_LAUNCHER='srun'");
}

#[test]
fn bare_jm_new_is_byte_identical_to_blank() {
    let ra = tempfile::tempdir().unwrap();
    let rb = tempfile::tempdir().unwrap();
    let pa = scaffold_print_path(&ra, &[]);
    let pb = scaffold_print_path(&rb, &["blank"]);
    let fa = normalize(&fs::read_to_string(pa.join("flow.toml")).unwrap());
    let fb = normalize(&fs::read_to_string(pb.join("flow.toml")).unwrap());
    assert_eq!(fa, fb);
}

#[test]
fn blank_plan_toml_parses_as_experiment_plan() {
    // Restores coverage of the deleted jm.rs `plan_template_parses_as_experiment_plan`.
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["blank"]);
    let plan_str = fs::read_to_string(dir.join("plan.toml")).unwrap();
    let _: job_manager::plan::ExperimentPlan =
        toml::from_str(&plan_str).expect("blank plan.toml must parse as ExperimentPlan");
}

#[test]
fn blank_tag_is_rendered_and_flow_still_parses_as_jobflow() {
    // Restores coverage of the deleted jm.rs `flow_template_renders_tags_section`.
    let root = tempfile::tempdir().unwrap();
    let dir = scaffold_print_path(&root, &["blank", "--tag", "owner=alice"]);
    let flow_str = fs::read_to_string(dir.join("flow.toml")).unwrap();
    assert!(
        flow_str.contains("owner = \"alice\""),
        "non-empty [tags] section must render the tag; got:\n{flow_str}"
    );
    // Still a valid JobFlow with the tag present.
    let _: gaussian_job_shared::entities::workflow::JobFlow =
        toml::from_str(&flow_str).expect("blank flow.toml with a tag must parse as JobFlow");
}
