#!/bin/bash
# Generated by job_manager SP-3. Do not edit; regenerated on every `jm run`.

# --- job-manager runtime context ---
export JM_FLOW_UUID='0199999a-0000-7000-8000-000000000001'
export JM_JOB_ID='freq__compound=2'
export JM_AXIS_COMPOUND='2'

# --- plan.toml params ---
export JM_PARAM_COMPOUND_NAME='p-xylene'
export JM_PARAM_ROUTE='B3LYP/6-31G* freq'

# --- user body (JobSpec.body) ---
echo "[$JM_JOB_ID] flow=$JM_FLOW_UUID compound=$JM_PARAM_COMPOUND_NAME route=$JM_PARAM_ROUTE"
sleep 2
