//! `blank` FlowRecipe — legacy 2-job echo DAG。**既存 `jm new` 出力と
//! バイト同値**(非分解・サイドカー/プリアンブル/R3' 焼込定数 無し)。`jm new` ≡
//! `jm new blank`。

use std::collections::BTreeMap;

pub fn parse_tag(raw: &str) -> anyhow::Result<(String, String)> {
    match raw.split_once('=') {
        Some(("", _)) => anyhow::bail!("invalid --tag: empty key in {raw:?}"),
        Some((k, _))
            if !k
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-') =>
        {
            anyhow::bail!(
                "invalid --tag: key {k:?} has non-bare-key characters (only A-Za-z0-9_- allowed)"
            )
        }
        Some((k, v)) => Ok((k.to_string(), v.to_string())),
        None => anyhow::bail!("invalid --tag: expected key=value, got {raw:?}"),
    }
}

pub fn build_plan_template() -> String {
    "\
# Generated by `jm new`. Per-JobId params surface in batch.bash as
# `JM_PARAM_<UPPER_NAME>`.
# Schema: job_manager::plan::ExperimentPlan (deny_unknown_fields)

[jobs.step1]
note = \"TODO: replace with real render params\"

[jobs.step2]
note = \"TODO: replace with real render params\"
"
    .to_string()
}

pub fn build_flow_template(
    uuid: &uuid::Uuid,
    created_at: &str,
    tags: &BTreeMap<String, String>,
) -> String {
    let mut tag_lines = String::new();
    if tags.is_empty() {
        tag_lines.push_str("# free-form key=value tags; populate via `jm new --tag k=v`\n");
    } else {
        for (k, v) in tags {
            let v_toml = toml::Value::String(v.clone()).to_string();
            tag_lines.push_str(&format!("{k} = {v_toml}\n"));
        }
    }
    format!(
        "\
# Generated by `jm new` on {created_at}.
# Schema: gaussian_job_shared::entities::workflow::JobFlow (deny_unknown_fields)
#   uuid          UUID v7 — MUST equal the parent directory name
#   created_at    RFC3339 UTC
#   jobs.<JobId>  JobSpec (program/body/config) + parents[]

uuid       = \"{uuid}\"
created_at = \"{created_at}\"

[tags]
{tag_lines}
# --- step 1: replace `program` / `body` with the real workload ---
[jobs.step1]
program = \"echo\"
body    = \"echo \\\"[step1] flow=$JM_FLOW_UUID job=$JM_JOB_ID\\\"\\n\"

[jobs.step1.config]
# `jm new` does NOT create common.toml, so `partition` is written here
# explicitly. REPLACE_ME makes `jm render` succeed but real `jm submit`
# fail fast with \"invalid partition: REPLACE_ME\" until you set a real
# partition (sinfo -s). Alternatively create <root>/common.toml with a
# [slurm_default] partition and delete this line to inherit it.
partition = \"REPLACE_ME\"

# --- step 2: runs only if step1 exits 0 ---
[jobs.step2]
program = \"echo\"
body    = \"echo \\\"[step2] flow=$JM_FLOW_UUID job=$JM_JOB_ID\\\"\\n\"

[[jobs.step2.parents]]
from = \"step1\"
kind = \"afterok\"

[jobs.step2.config]
partition = \"REPLACE_ME\"
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_tag_splits_on_first_equals() {
        assert_eq!(parse_tag("a=b").unwrap(), ("a".into(), "b".into()));
    }
    #[test]
    fn parse_tag_keeps_later_equals_in_value() {
        assert_eq!(parse_tag("a=b=c").unwrap(), ("a".into(), "b=c".into()));
    }
    #[test]
    fn parse_tag_rejects_missing_equals() {
        assert!(
            parse_tag("abc")
                .unwrap_err()
                .to_string()
                .contains("expected key=value")
        );
    }
    #[test]
    fn parse_tag_rejects_empty_key() {
        assert!(
            parse_tag("=v")
                .unwrap_err()
                .to_string()
                .contains("empty key")
        );
    }
    #[test]
    fn parse_tag_rejects_non_bare_key() {
        for bad in ["my key=v", "my.key=v", "k!=v"] {
            assert!(
                parse_tag(bad)
                    .unwrap_err()
                    .to_string()
                    .contains("non-bare-key")
            );
        }
    }
    #[test]
    fn blank_flow_template_parses_as_jobflow() {
        let u = uuid::Uuid::now_v7();
        let f = build_flow_template(&u, "2026-05-18T00:00:00Z", &BTreeMap::new());
        let _: gaussian_job_shared::entities::workflow::JobFlow =
            toml::from_str(&f).expect("blank flow.toml must parse");
        assert!(f.contains("[jobs.step1]") && f.contains("[jobs.step2]"));
        assert_eq!(f.matches("partition = \"REPLACE_ME\"").count(), 2);
    }
}
