"""Regenerate examples/sweep/inputs/<uuid>/{flow.toml, plan.toml}.

Run from the repo root after ``uv sync && uv run maturin develop``::

    uv run python examples/sweep/author.py

Idempotent — overwrites the two TOML files under the committed uuid
**byte-for-byte** (modulo the trailing newline). ``common.toml`` is
not regenerated (cluster-specific sentinels), and ``inputs-fail/``
is left alone (it's a hand-edited single-line variant).

Why ``Path.write_text`` instead of ``write_flow``/``write_plan``:
the Rust TOML serializer reorders keys alphabetically and strips
comments, so the round-tripped output wouldn't match the
documentation-rich hand-authored format committed under ``inputs/``.
We use the Python ``job_manager`` API for:

* ``build_job_id`` — derive sweep JobIds (``opt__compound=N``)
  identically to the rest of the system
* ``read_flow``/``read_plan`` — round-trip the output we just wrote
  through the Rust parser to catch any TOML syntax error before
  saving

Dependencies: only the ``job_manager`` package (already installed by
``maturin develop``).
"""

from __future__ import annotations

from pathlib import Path

from job_manager import build_job_id, read_flow, read_plan

UUID = "0199999a-0000-7000-8000-000000000000"
CREATED_AT = "2026-05-15T00:00:00Z"

COMPOUNDS: list[tuple[int, str]] = [
    (0, "benzene"),
    (1, "toluene"),
    (2, "p-xylene"),
]
ROUTE_OPT = "B3LYP/6-31G* opt"
ROUTE_FREQ = "B3LYP/6-31G* freq"
PARTITION_SENTINEL = "REPLACE_ME"

BODY_TOML = (
    '"echo \\"[$JM_JOB_ID] flow=$JM_FLOW_UUID '
    'compound=$JM_PARAM_COMPOUND_NAME route=$JM_PARAM_ROUTE\\"\\nsleep 2\\n"'
)


_FLOW_HEADER = """\
# JobFlow — sweep + fan-out DAG.
#
# Shape (7 nodes, 6 afterok edges):
#
#                              prep
#                  ┌─────────────┼─────────────┐
#                  ▼             ▼             ▼
#        opt__compound=0  opt__compound=1  opt__compound=2
#                  │             │             │
#                  ▼             ▼             ▼
#        freq__compound=0 freq__compound=1 freq__compound=2
#
# Sweep axis: `compound ∈ {0=benzene, 1=toluene, 2=p-xylene}`.
# JobIds with `=` (build_job_id output) must be quoted in TOML table headers.
#
# `body` reads two render-time params surfaced as env exports by
# `render_batch_bash`: `JM_PARAM_COMPOUND_NAME` and `JM_PARAM_ROUTE`.
# Values come from the sibling plan.toml (`[jobs.<JobId>].compound_name`,
# `[jobs.<JobId>].route`). `prep` has compound_name = "" so its line
# renders as `compound=` — that's intentional, to show the export is
# always defined.
#
# Per-job `[jobs.X.config].partition = "REPLACE_ME"` exists so
# `merge_with_defaults` exercises the per-job override path (non-empty
# wins over common.toml). Rewrite both the per-job and common-level
# partitions before submit, or sbatch will reject "invalid partition
# specified: REPLACE_ME".
#
# This file is regenerated byte-for-byte by ../author.py.
"""

_PLAN_HEADER = """\
# ExperimentPlan — per-JobId render params, surfaced into batch.bash as
# `JM_PARAM_<UPPER_NAME>` env exports by `render_batch_bash`.
#
# Schema: job_manager::plan::ExperimentPlan (deny_unknown_fields)
#   jobs.<JobId> : BTreeMap<String, toml::Value>
#
# Every JobId in flow.toml has a corresponding entry here. `prep` carries
# only a `route = "bootstrap"` marker plus an empty `compound_name` to
# keep the export defined.
#
# `route` here is demo text (the body is plain `echo`, not g16). The
# point is that `plan.toml` is the single place to vary params across a
# sweep without editing `flow.toml`.
#
# This file is regenerated byte-for-byte by ../author.py.
"""


def _job_block(job_id: str, parents: list[str], partition_comment: str = "") -> str:
    quoted = f'"{job_id}"' if "=" in job_id else job_id
    out = [
        f"[jobs.{quoted}]",
        'program = "echo"',
        f"body    = {BODY_TOML}",
        "",
    ]
    for parent in parents:
        out.extend(
            [
                f"[[jobs.{quoted}.parents]]",
                f'from = "{parent}"',
                'kind = "afterok"',
                "",
            ]
        )
    suffix = f"   # {partition_comment}" if partition_comment else ""
    out.extend(
        [
            f"[jobs.{quoted}.config]",
            f'partition = "{PARTITION_SENTINEL}"{suffix}',
            "",
        ]
    )
    return "\n".join(out)


def build_flow_toml() -> str:
    opt_ids = [build_job_id("opt", [("compound", idx)]) for idx, _ in COMPOUNDS]
    freq_ids = [build_job_id("freq", [("compound", idx)]) for idx, _ in COMPOUNDS]

    parts = [
        _FLOW_HEADER,
        f'uuid       = "{UUID}"',
        f'created_at = "{CREATED_AT}"',
        "",
        "[tags]",
        'example = "sweep"',
        'variant = "success"',
        "",
        "# --- root step ---",
        _job_block(
            "prep",
            parents=[],
            partition_comment=(
                "← merge_with_defaults takes this over common.toml "
                "when non-empty; rewrite both before submit"
            ),
        ),
        "# --- opt branches (3-way fan-out from prep) ---",
    ]
    for opt_id in opt_ids:
        parts.append(_job_block(opt_id, parents=["prep"]))
    parts.append("# --- freq branches (one linear afterok per opt) ---")
    for opt_id, freq_id in zip(opt_ids, freq_ids):
        parts.append(_job_block(freq_id, parents=[opt_id]))

    body = "\n".join(parts)
    # Strip a single trailing blank line so the file ends with exactly one
    # newline — matches the hand-authored format.
    while body.endswith("\n\n"):
        body = body[:-1]
    if not body.endswith("\n"):
        body += "\n"
    return body


def build_plan_toml() -> str:
    parts = [
        _PLAN_HEADER,
        "[jobs.prep]",
        'compound_name = ""',
        'route         = "bootstrap"',
        "",
        "# --- opt branches: 3-way sweep on compound ---",
    ]
    for idx, name in COMPOUNDS:
        opt_id = build_job_id("opt", [("compound", idx)])
        parts.extend(
            [
                f'[jobs."{opt_id}"]',
                f'compound_name = "{name}"',
                f'route         = "{ROUTE_OPT}"',
                "",
            ]
        )
    parts.append("# --- freq branches: same sweep, downstream step ---")
    for idx, name in COMPOUNDS:
        freq_id = build_job_id("freq", [("compound", idx)])
        parts.extend(
            [
                f'[jobs."{freq_id}"]',
                f'compound_name = "{name}"',
                f'route         = "{ROUTE_FREQ}"',
                "",
            ]
        )

    body = "\n".join(parts)
    while body.endswith("\n\n"):
        body = body[:-1]
    if not body.endswith("\n"):
        body += "\n"
    return body


def main() -> None:
    here = Path(__file__).resolve().parent
    flow_path = here / "inputs" / UUID / "flow.toml"
    plan_path = here / "inputs" / UUID / "plan.toml"
    flow_path.parent.mkdir(parents=True, exist_ok=True)

    flow_path.write_text(build_flow_toml())
    plan_path.write_text(build_plan_toml())

    # Round-trip: catch any TOML syntax error before claiming success.
    read_flow(str(flow_path))
    parsed_plan = read_plan(str(plan_path))
    expected_ids = {
        "prep",
        *(build_job_id("opt", [("compound", i)]) for i, _ in COMPOUNDS),
        *(build_job_id("freq", [("compound", i)]) for i, _ in COMPOUNDS),
    }
    got_ids = set(parsed_plan.jobs.keys())
    if got_ids != expected_ids:
        raise SystemExit(
            f"plan jobs mismatch: expected {sorted(expected_ids)}, got {sorted(got_ids)}"
        )

    rel_flow = flow_path.relative_to(here.parent.parent)
    rel_plan = plan_path.relative_to(here.parent.parent)
    print(f"wrote {rel_flow}")
    print(f"wrote {rel_plan}")


if __name__ == "__main__":
    main()
