//! batch.bash render — env-export style with POSIX single-quote escaping.

use crate::jobid::JobIdParts;
use gaussian_job_shared::entities::workflow::JobId;
use std::collections::BTreeMap;
use uuid::Uuid;

/// Convert an axis name or param key into a bash-safe upper-case identifier.
pub fn sanitize_var_name(name: &str) -> String {
    let upper = name.to_ascii_uppercase();
    upper
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// POSIX-safe single-quote escape: `'` → `'\''`, then wrap in single quotes.
pub fn quote_for_bash(value: &str) -> String {
    let escaped = value.replace('\'', r"'\''");
    format!("'{escaped}'")
}

/// Render a batch.bash script with env-export style (JM_* variables).
/// Generates:
/// - `#!/bin/bash` shebang
/// - Job context: `JM_FLOW_UUID`, `JM_JOB_ID`
/// - Axes: `JM_AXIS_<NAME>` for each (axis, idx) in axis_combo
/// - Params: `JM_PARAM_<NAME>` for each (k, v) in params
/// - User body (JobSpec.body)
///
/// All values are quoted with `quote_for_bash` for POSIX safety.
pub fn render_batch_bash(
    flow_uuid: &Uuid,
    jid: &JobId,
    parts: &JobIdParts<'_>,
    params: &BTreeMap<String, toml::Value>,
    body: &str,
) -> String {
    let mut s = String::new();
    s.push_str("#!/bin/bash\n");
    s.push_str("# Generated by job_manager SP-3. Do not edit; regenerated on every `jm run`.\n");
    s.push_str("\n# --- job-manager runtime context ---\n");
    s.push_str(&format!(
        "export JM_FLOW_UUID={}\n",
        quote_for_bash(&flow_uuid.to_string())
    ));
    s.push_str(&format!("export JM_JOB_ID={}\n", quote_for_bash(&jid.0)));
    for (axis, idx) in &parts.axis_combo {
        let key = sanitize_var_name(axis);
        s.push_str(&format!(
            "export JM_AXIS_{}={}\n",
            key,
            quote_for_bash(&idx.to_string())
        ));
    }
    s.push_str("\n# --- plan.toml params ---\n");
    for (k, v) in params {
        let key = sanitize_var_name(k);
        let val = toml_value_to_string(v);
        s.push_str(&format!(
            "export JM_PARAM_{}={}\n",
            key,
            quote_for_bash(&val)
        ));
    }
    s.push_str("\n# --- user body (JobSpec.body) ---\n");
    s.push_str(body);
    if !body.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// Convert a toml::Value to its string representation for env export.
fn toml_value_to_string(v: &toml::Value) -> String {
    match v {
        toml::Value::String(s) => s.clone(),
        toml::Value::Integer(i) => i.to_string(),
        toml::Value::Float(f) => f.to_string(),
        toml::Value::Boolean(b) => b.to_string(),
        toml::Value::Array(a) => {
            let parts: Vec<String> = a.iter().map(toml_value_to_string).collect();
            parts.join(" ")
        }
        toml::Value::Datetime(d) => d.to_string(),
        toml::Value::Table(_) => format!("{v}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_upper_cases_lowercase() {
        assert_eq!(sanitize_var_name("compound"), "COMPOUND");
    }

    #[test]
    fn sanitize_replaces_hyphen() {
        assert_eq!(sanitize_var_name("my-axis"), "MY_AXIS");
    }

    #[test]
    fn sanitize_replaces_dot() {
        assert_eq!(sanitize_var_name("ax.is"), "AX_IS");
    }

    #[test]
    fn quote_simple_value() {
        assert_eq!(quote_for_bash("hello"), "'hello'");
    }

    #[test]
    fn quote_escapes_single_quote() {
        assert_eq!(quote_for_bash("it's"), r"'it'\''s'");
    }

    #[test]
    fn quote_preserves_newline() {
        assert_eq!(quote_for_bash("a\nb"), "'a\nb'");
    }

    #[test]
    fn render_batch_bash_produces_expected_sections() {
        use crate::jobid::JobIdParts;
        use gaussian_job_shared::entities::workflow::JobId;
        use std::collections::BTreeMap;
        use uuid::Uuid;

        let flow_uuid = Uuid::parse_str("01997cdc-0000-7000-8000-000000000000").unwrap();
        let jid = JobId("opt__compound=0__method=1".to_string());
        let parts = JobIdParts {
            source_step_id: "opt",
            axis_combo: vec![("compound", 0), ("method", 1)],
        };
        let mut params: BTreeMap<String, toml::Value> = BTreeMap::new();
        params.insert(
            "route".to_string(),
            toml::Value::String("# B3LYP/6-31G*".to_string()),
        );
        params.insert("nproc".to_string(), toml::Value::Integer(16));
        let body = "#!/bin/bash\necho hello";

        let out = render_batch_bash(&flow_uuid, &jid, &parts, &params, body);

        assert!(out.starts_with("#!/bin/bash"));
        assert!(out.contains("export JM_FLOW_UUID='01997cdc-0000-7000-8000-000000000000'"));
        assert!(out.contains("export JM_JOB_ID='opt__compound=0__method=1'"));
        assert!(out.contains("export JM_AXIS_COMPOUND='0'"));
        assert!(out.contains("export JM_AXIS_METHOD='1'"));
        assert!(out.contains("export JM_PARAM_ROUTE='# B3LYP/6-31G*'"));
        assert!(out.contains("export JM_PARAM_NPROC='16'"));
        assert!(out.contains(body));
    }

    #[test]
    fn render_batch_bash_escapes_single_quote_in_param() {
        use crate::jobid::JobIdParts;
        use gaussian_job_shared::entities::workflow::JobId;
        use std::collections::BTreeMap;
        use uuid::Uuid;

        let flow_uuid = Uuid::parse_str("01997cdc-0000-7000-8000-000000000000").unwrap();
        let jid = JobId("x__a=0".to_string());
        let parts = JobIdParts {
            source_step_id: "x",
            axis_combo: vec![("a", 0)],
        };
        let mut params: BTreeMap<String, toml::Value> = BTreeMap::new();
        params.insert(
            "note".to_string(),
            toml::Value::String("it's working".to_string()),
        );

        let out = render_batch_bash(&flow_uuid, &jid, &parts, &params, "");
        assert!(
            out.contains(r"export JM_PARAM_NOTE='it'\''s working'"),
            "got: {out}"
        );
    }
}
