#!/bin/bash
# Generated by job_manager SP-3. Do not edit; regenerated on every `jm run`.

# --- job-manager runtime context ---
export JM_FLOW_UUID='01999999-0000-7000-8000-000000000000'
export JM_JOB_ID='opt'

# --- plan.toml params ---
export JM_PARAM_NOTE='first step: pretend we run an optimization'
export JM_PARAM_NPROC='1'
export JM_PARAM_ROUTE='echo-only'

# --- user body (JobSpec.body) ---
echo "[opt] flow=$JM_FLOW_UUID job=$JM_JOB_ID"
sleep 2
