#!/bin/bash
# Generated by job_manager SP-3. Do not edit; regenerated on every `jm run`.

# --- job-manager runtime context ---
export JM_FLOW_UUID='0199999a-0000-7000-8000-000000000001'
export JM_JOB_ID='opt__compound=1'
export JM_AXIS_COMPOUND='1'

# --- plan.toml params ---
export JM_PARAM_COMPOUND_NAME='toluene'
export JM_PARAM_ROUTE='B3LYP/6-31G* opt'

# --- user body (JobSpec.body) ---
echo "[$JM_JOB_ID] simulated failure: $JM_PARAM_COMPOUND_NAME"
exit 1
